# DL Features Classification 

In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
import pandas as pd
from IPython.html import widgets
from IPython.html.widgets import interact
from IPython.display import display
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import numpy as np

/home/aditya/anaconda2/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/aditya/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('./Data/Balanced_DL_Features.csv', header=None)
print df.shape

X = df.values[:,0:1200]
Y = df.values[:,1201:1202]
print X.shape
print Y.shape

(600, 1202)
(600, 1200)
(600, 1)


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)


### Naive Bayes

In [4]:
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
y_pred1 = model_nb.predict(X_test)
print metrics.classification_report(y_test, y_pred1)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred1)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred1)

             precision    recall  f1-score   support

        0.0       0.61      0.60      0.61        96
        1.0       0.55      0.56      0.56        84

avg / total       0.58      0.58      0.58       180

confusion matrix: 
[[58 38]
 [37 47]]
accuracy score:  0.583333333333


/home/aditya/anaconda2/lib/python2.7/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Decision Tree

In [5]:
def DT(num):
    model_dt = DecisionTreeClassifier(max_depth=num)
    model_dt.fit(X_train, y_train)
    y_pred2 = model_dt.predict(X_test)
    print metrics.classification_report(y_test, y_pred2)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred2)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred2)

In [6]:
i = interact(DT, num=(1,20))

#Best at 5

             precision    recall  f1-score   support

        0.0       0.59      0.68      0.63        96
        1.0       0.55      0.45      0.50        84

avg / total       0.57      0.57      0.57       180

confusion matrix: 
[[65 31]
 [46 38]]
accuracy score:  0.572222222222


### Random Forest

In [7]:
def RF(num):
    model_rf = RandomForestClassifier(criterion='entropy',n_estimators=num)
    model_rf.fit(X_train, y_train)
    y_pred3 = model_rf.predict(X_test)
    print metrics.classification_report(y_test, y_pred3)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred3)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred3)


In [8]:
i = interact(RF, num=(1,50))

#Best at 16 for Balanced DL Features

/home/aditya/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


             precision    recall  f1-score   support

        0.0       0.62      0.64      0.63        96
        1.0       0.57      0.56      0.57        84

avg / total       0.60      0.60      0.60       180

confusion matrix: 
[[61 35]
 [37 47]]
accuracy score:  0.6


### SVM

In [9]:
model_svm = svm.SVC(kernel='rbf', gamma = 0.00083)
model_svm.fit(X_train, y_train)
y_pred4 = model_svm.predict(X_test)
print metrics.classification_report(y_test, y_pred4)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred4)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred4)

#Gamma = 1/num_features

             precision    recall  f1-score   support

        0.0       0.76      0.54      0.63        96
        1.0       0.61      0.81      0.69        84

avg / total       0.69      0.67      0.66       180

confusion matrix: 
[[52 44]
 [16 68]]
accuracy score:  0.666666666667


### KNN

In [10]:
def KNN(num):
    model_knn = KNeighborsClassifier(n_neighbors=num)
    model_knn.fit(X_train, y_train)
    y_pred5 = model_knn.predict(X_test)
    print metrics.classification_report(y_test, y_pred4)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred5)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred5)

In [11]:
KNN(24)

# KNN Thumb Rule for N: root(Num_Samples)

             precision    recall  f1-score   support

        0.0       0.76      0.54      0.63        96
        1.0       0.61      0.81      0.69        84

avg / total       0.69      0.67      0.66       180

confusion matrix: 
[[80 16]
 [46 38]]
accuracy score:  0.655555555556


/home/aditya/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  app.launch_new_instance()
