# Chokepoint Classification 

In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
import pandas as pd
from IPython.html import widgets
from IPython.html.widgets import interact
from IPython.display import display
from sklearn.cross_validation import train_test_split
from sklearn import metrics
import numpy as np
from sklearn.metrics import roc_curve, auc
from scipy import interp
import matplotlib.pyplot as plt
from itertools import cycle


/home/admin1/anaconda2/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/admin1/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('./Data/Classification_Dataset.csv')
df

Brightness  FaceArea   Sharpness  EyesDistance  MouthDistance  \
0       28.721546  1.003208  162.066102      0.326623       0.266900   
1       30.817011  0.955632   50.472411      0.329842       0.227280   
2       49.386166  0.721411   58.588165      0.350090       0.283679   
3       37.276478  0.748891  254.853094      0.339438       0.221756   
4       33.498543  0.748891  273.242966      0.302376       0.216229   
5       42.453091  0.591716   49.957179      0.314596       0.228642   
6       45.174900  0.791073   64.809343      0.334807       0.267335   
7       28.935623  1.187541  233.220835      0.337993       0.248478   
8       29.668480  0.947799   64.632192      0.329297       0.321298   
9        0.000000  0.000000  259.192189      0.000000       0.000000   
10      23.603483  0.849115   37.685119      0.317771       0.267990   
11      18.563124  0.791073  101.640405      0.347660       0.288419   
12      48.151733  0.776884  278.662218      0.304013       0.222630   
13      42.102028  0.735086   53.975158      0.327796       0.237176   
14      24.985128  0.834412  274.403006      0.299895       0.219765   
15      40.099644  0.748891  108.402428      0.322537       0.252055   
16      26.610985  0.987221  309.142608      0.340208       0.250482   
17      42.403271  0.674541   89.104172      0.324571       0.284493   
18      38.684399  0.748891  253.544569      0.335448       0.272425   
19      25.665012  0.762823   51.227891      0.318734       0.240523   
20      41.338806  0.924556   87.074197      0.328622       0.263917   
21      42.598389  0.783947   47.470539      0.336709       0.271968   
22      33.043808  0.909211  283.820081      0.345020       0.281379   
23      28.809786  1.205069   62.700858      0.339794       0.280091   
24      54.263733  0.629276  217.894609      0.269618       0.173196   
25      40.374470  1.019323   30.355622      0.326990       0.232846   
26      35.820786  0.893995  264.883790      0.318421       0.257727   
27      29.320204  0.819837   66.953666      0.341541       0.286928   
28      38.708790  0.955632  110.281486      0.339712       0.254853   
29       0.000000  0.000000   78.465355      0.000000       0.000000   
...           ...       ...         ...           ...            ...   
28975   40.514614  0.748891  264.313076      0.332188       0.235584   
28976   44.890583  0.735086   57.306533      0.347297       0.224702   
28977   44.446518  0.776884  194.556226      0.338546       0.243247   
28978   41.821259  0.849115   40.172824      0.327721       0.267921   
28979   48.792549  0.834412  229.697436      0.327925       0.256366   
28980   22.028605  1.135728   57.189739      0.341543       0.265397   
28981    0.000000  0.000000  188.273218      0.000000       0.000000   
28982    0.000000  0.000000   54.496849      0.000000       0.000000   
28983   46.645657  0.707863  229.761386      0.376624       0.246530   
28984   49.434521  0.667992  249.028631      0.342908       0.248228   
28985   27.969086  1.368600  112.591755      0.350803       0.321457   
28986    0.000000  0.000000  197.712782      0.000000       0.000000   
28987    0.000000  0.000000  186.379670      0.000000       0.000000   
28988    0.000000  0.000000  157.259486      0.000000       0.000000   
28989   42.398678  0.805391  185.573937      0.326711       0.260435   
28990    0.000000  0.000000  122.854589      0.000000       0.000000   
28991    0.000000  0.000000   96.754955      0.000000       0.000000   
28992    0.000000  0.000000   80.907582      0.000000       0.000000   
28993   38.090897  0.971362  391.718628      0.339784       0.282976   
28994   30.987406  1.170141  410.902655      0.350677       0.296838   
28995   39.025101  1.101827  241.872239      0.358344       0.292652   
28996   46.849594  0.893995  187.187720      0.342294       0.220129   
28997   39.162624  0.762823  139.772406      0.320585       0.247860   
28998   48.856678  0.819837  367.352675      0.

In [4]:
X = df[['Brightness', 'FaceArea', 'Sharpness', 'EyesDistance', 'MouthDistance', 'Eyeglass','EyesOpen','Gender', 'Beard', 'Moustache']].values

Y = df[['Quality']].values

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=0)


In [6]:
print X.shape
print Y.shape

(29005, 10)
(29005, 1)


In [154]:
font = {'family' : 'normal',
        'weight' : 'normal',
        'size'   : 30}

plt.rc('font', **font)

### Naive Bayes

In [155]:
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)
y_pred1 = model_nb.predict(X_test)
print metrics.classification_report(y_test, y_pred1)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred1)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred1)

             precision    recall  f1-score   support

          0       0.62      0.85      0.71      4231
          1       0.78      0.50      0.61      4471

avg / total       0.70      0.67      0.66      8702

confusion matrix: 
[[3589  642]
 [2229 2242]]
accuracy score:  0.670075844633


In [156]:
fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred1)
roc_auc = metrics.auc(fpr, tpr)

plt.title('ROC - Gaussian Naive Bayes')
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 13
plt.rcParams["figure.figsize"] = fig_size
plt.plot(fpr, tpr, 'cyan', label = 'NB AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right' , fontsize = 25)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])1000
plt.ylabel('True Positive Rate',fontsize=20)
plt.xlabel('False Positive Rate',fontsize=20)
plt.colors
#plt.show()

#plt.savefig('./Images/ROC_NB.eps', format='eps', dpi=1000)

<function matplotlib.pyplot.colors>

### Decision Tree

In [157]:
def DT(num):
    model_dt = DecisionTreeClassifier(max_depth=num)
    model_dt.fit(X_train, y_train)
    y_pred2 = model_dt.predict(X_test)
    print metrics.classification_report(y_test, y_pred2)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred2)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred2)
    return y_pred2

In [158]:
#i = interact(DT, num=(1,20))
y_pred2 = DT(5)
#Best at 5

             precision    recall  f1-score   support

          0       0.66      0.70      0.68      4231
          1       0.70      0.66      0.68      4471

avg / total       0.68      0.68      0.68      8702

confusion matrix: 
[[2949 1282]
 [1521 2950]]
accuracy score:  0.677890140198


In [159]:
model_dt = DecisionTreeClassifier(max_depth=5)
model_dt.fit(X_train, y_train)
y_pred2 = model_dt.predict(X_test)
print metrics.classification_report(y_test, y_pred2)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred2)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred2)


fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred2)
roc_auc = metrics.auc(fpr, tpr)

plt.title('ROC - Decision Tree')
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 13
plt.rcParams["figure.figsize"] = fig_size
plt.plot(fpr, tpr, 'g', label = 'DT AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right', fontsize = 25)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate',fontsize=20)
plt.xlabel('False Positive Rate',fontsize=20)
#plt.show()

#plt.savefig('./Images/ROC_DT.eps', format='eps', dpi=1000)

             precision    recall  f1-score   support

          0       0.66      0.70      0.68      4231
          1       0.70      0.66      0.68      4471

avg / total       0.68      0.68      0.68      8702

confusion matrix: 
[[2949 1282]
 [1521 2950]]
accuracy score:  0.677890140198


Text(0.5,0,u'False Positive Rate')

### Random Forest

In [160]:
def RF(num):
    model_rf = RandomForestClassifier(criterion='entropy',n_estimators=num)
    model_rf.fit(X_train, y_train)
    y_pred3 = model_rf.predict(X_test)
    print metrics.classification_report(y_test, y_pred3)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred3)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred3)


In [161]:
#i = interact(RF, num=(1,50))
RF(23)
#Best at 23

/home/admin1/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  app.launch_new_instance()


             precision    recall  f1-score   support

          0       0.60      0.69      0.64      4231
          1       0.66      0.55      0.60      4471

avg / total       0.63      0.62      0.62      8702

confusion matrix: 
[[2940 1291]
 [1991 2480]]
accuracy score:  0.622845322914


In [162]:
model_rf = RandomForestClassifier(criterion='entropy',n_estimators=23)
model_rf.fit(X_train, y_train)
y_pred3 = model_rf.predict(X_test)
print metrics.classification_report(y_test, y_pred3)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred3)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred3)

fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred3)
roc_auc = metrics.auc(fpr, tpr)

plt.title('ROC - Random Forest')
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 13
plt.rcParams["figure.figsize"] = fig_size
plt.plot(fpr, tpr, 'm', label = 'RF AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right' , fontsize = 25)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate',fontsize=20)
plt.xlabel('False Positive Rate',fontsize=20)
#plt.show()

#plt.savefig('./Images/ROC_RF.eps', format='eps', dpi=1000)

/home/admin1/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from ipykernel import kernelapp as app


             precision    recall  f1-score   support

          0       0.60      0.71      0.65      4231
          1       0.67      0.56      0.61      4471

avg / total       0.64      0.63      0.63      8702

confusion matrix: 
[[3006 1225]
 [1971 2500]]
accuracy score:  0.632728108481


Text(0.5,0,u'False Positive Rate')

### SVM

In [163]:
model_svm = svm.SVC(kernel='rbf', gamma = 0.1)
model_svm.fit(X_train, y_train)
y_pred4 = model_svm.predict(X_test)
print metrics.classification_report(y_test, y_pred4)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred4)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred4)

#Gamma = 1/num_features

fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred4)
roc_auc = metrics.auc(fpr, tpr)

plt.title('ROC - SVM')
fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 13
plt.rcParams["figure.figsize"] = fig_size
plt.plot(fpr, tpr, 'y', label = 'SVM AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right' , fontsize = 25)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate',fontsize=20)
plt.xlabel('False Positive Rate',fontsize=20)
#plt.show()

#plt.savefig('./Images/ROC_SVM.eps', format='eps', dpi=1000)

             precision    recall  f1-score   support

          0       0.63      0.73      0.68      4231
          1       0.70      0.60      0.64      4471

avg / total       0.67      0.66      0.66      8702

confusion matrix: 
[[3082 1149]
 [1805 2666]]
accuracy score:  0.660537807401


Text(0.5,0,u'False Positive Rate')

### KNN

In [164]:
def KNN(num):
    model_knn = KNeighborsClassifier(n_neighbors=num)
    model_knn.fit(X_train, y_train)
    y_pred5 = model_knn.predict(X_test)
    print metrics.classification_report(y_test, y_pred4)
    print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred5)
    print "accuracy score: " , metrics.accuracy_score(y_test, y_pred5)

In [165]:
KNN(170)

# KNN Thumb Rule for N: root(Num_Samples)

/home/admin1/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  app.launch_new_instance()


             precision    recall  f1-score   support

          0       0.63      0.73      0.68      4231
          1       0.70      0.60      0.64      4471

avg / total       0.67      0.66      0.66      8702

confusion matrix: 
[[3512  719]
 [2159 2312]]
accuracy score:  0.669271431855


In [166]:
model_knn = KNeighborsClassifier(n_neighbors=170)
model_knn.fit(X_train, y_train)
y_pred5 = model_knn.predict(X_test)
print metrics.classification_report(y_test, y_pred4)
print "confusion matrix: \n" , metrics.confusion_matrix(y_test, y_pred5)
print "accuracy score: " , metrics.accuracy_score(y_test, y_pred5)

fpr, tpr, threshold = metrics.roc_curve(y_test, y_pred5)
roc_auc = metrics.auc(fpr, tpr)

plt.title('ROC')

fig_size = plt.rcParams["figure.figsize"]
fig_size[0] = 16
fig_size[1] = 13
plt.rcParams["figure.figsize"] = fig_size

plt.plot(fpr, tpr, 'b',label = 'KNN AUC = %0.2f' % roc_auc)
plt.legend(loc = 'lower right' , fontsize = 25)
plt.plot([0, 1], [0, 1],'r--')
plt.xlim([0, 1])
plt.ylim([0, 1])
plt.ylabel('True Positive Rate',fontsize=30)
plt.xlabel('False Positive Rate',fontsize=30)
#plt.show()

plt.savefig('./Images/ROC_eps.eps', format='eps', dpi=1000)
plt.savefig('./Images/ROC_png.png', format='png', dpi=1000)

/home/admin1/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  from ipykernel import kernelapp as app


             precision    recall  f1-score   support

          0       0.63      0.73      0.68      4231
          1       0.70      0.60      0.64      4471

avg / total       0.67      0.66      0.66      8702

confusion matrix: 
[[3512  719]
 [2159 2312]]
accuracy score:  0.669271431855
